[package]
name = "gbnf"
version = "0.1.0"
edition = "2021"
description = "A libray for working with GBNF"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.3"
